name: Validate

on:
  push:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "parser/**"
      - "site/**"
      - "pad/**"
      - "tests*/**"
      - "changelog.md"
      - "readme.md"
      - ".github/workflows/validate.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "parser/**"
      - "site/**"
      - "pad/**"
      - "tests*/**"
      - "changelog.md"
      - "readme.md"
      - ".github/workflows/validate.yml"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all --check
    - name: Install depsAdd commentMore actions
      run: |
        sudo apt-get update -y
        sudo apt-get --fix-missing install -y
        sudo apt-get install libasound2-dev libudev-dev pkg-config libx11-dev libjpeg-dev
    - name: Install WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Check feature combinations
      run: cargo run ./.github/features.ua
